spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxclustercourse.bqmyxft.mongodb.net/${DB_NAME:webflux-course-db}?retryWrites=true&w=majority
  application:
    name: webflux-course